# Page settings
baseurl = "localhost:1313"
title = "Spoke Bikes"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Dan Vogel"
  description = "Spoke Bikes Site"
  email = "dhvogel2468@gmail.com"
  # Navigation
  [params.navigation]
    brand = "Spoke"
    home = "Home"
    work = "How It Works"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Bikes are complicated."
    subtitle = 'We can help.'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Discover"
    description = "Find the bike of your dreams."
    url = "#"
    button = "Take our quiz"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Customize"
    description = "Accessories earn style points."
    url = "#"
    button = "Accessorize"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "We'll bring the bike to you."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=K1ljOcl39PQ"


  # Work section
  [params.work]
    enable = true
    title = "How it works"
    description = "It's simple, you see."
    footertext = ''

    [[params.work.row]]
      img = "work_1.png"
      alt = "Image2"
      title = "Step 1"
      subtitle = "Find a bike"

    [[params.work.row]]
      img = "work_2.svg"
      alt = "Image2"
      title = "Step 2"
      subtitle = "?"

    [[params.work.row]]
      img = "work_3.png"
      alt = "Image3"
      title = "Step 3"
      subtitle = "We both profit"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "This is how much people love Spoke."

    [[params.testimonials.item]]
      quote = "&ldquo;Spoke. So hot right now. Spoke.&rdquo;"
      person = 'Mugatu, CEO <a href="http://freehtml5.co/" target="_blank"></a> <span class="subtext">Mugatu Enterprises</span>'
      img = "person1.png"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Dagger!!!!!!&rdquo;"
      person = 'Trevor Ariza, Shooting Guard<a href="http://freehtml5.co/" target="_blank"></a> <span class="subtext">Toronto Raptors</span>'
      img = "person2.png"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Who do you think you are?? I am!!!!&rdquo;"
      person = 'Pete Weber, Bad Boy of Bowling <a href="http://freehtml5.co/" target="_blank"></a> <span class="subtext">PBA</span>'
      img = "person3.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "We do these things!!"

    [[params.services.item]]
      title = "Discovery"
      description = "Our patented bicycle search algorithm backed by a rule-based engine (AI if you're an investor) will help you find a bike."
      icon = "icon-search"

    [[params.services.item]]
      title = "Procurement"
      description = "Using our advanced logistics technology, we will find the optimal route to bring the bike to your door."
      icon = "icon-direction"

    [[params.services.item]]
      title = "Servicing &amp; Insurance"
      description = "We'll be there for you for the long haul."
      icon = "icon-shield"

      [[params.services.item]]
      title = "Enterprise"
      description = "We manage bike logistics for large companies."
      icon = "icon-briefcase"

  # About section
  [params.about]
    enable = true
    title = "About Us"
    description = "The Co-Founders"

    [[params.about.item]]
      name = "Josh Miller"
      position = "Big Cheddar"
      description = "A top lad"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Dan Vogel"
      position = "Playmaker"
      description = "A real guy"
      img = "person2-dan.png"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Businesses served"
      icon = "icon-briefcase"
      from = 0
      to = 100
      interval = 50
      speed = 1000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1000
      interval = 50
      speed = 2000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 10000
      interval = 50
      speed = 3000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 100000
      interval = 50
      speed = 4000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Reach out!"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "San Francisco, CA"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "weneedanemail@gmail.com"],
        ["icon-globe", '<a href="http://spoke.bike/" target="_blank">spoke.bike</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '© Spoke Bikes 2018'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
